# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_reg', '0002_auto_20170124_0211'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
