# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_reg', '0003_auto_20170126_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='pw_hashed',
        ),
    ]
