# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_and_reg', '0004_auto_20170126_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('item_user', models.ManyToManyField(to='login_and_reg.User')),
                ('logged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_item', to='login_and_reg.User')),
            ],
        ),
    ]
